### ISSUE TITLE
GetIntAt returns always positive result

### ISSUE THREAD

**Issue by lupal1** [mesta1/Sharp7-example#1]
There is no sign handeled in function GetIntAt.

**Comment by mesta1** [comment]
Please post a sample code, I used it and it was returning the correct value.

**Comment by lupal1** [comment]
Hello,
Let's use:

        private void WriteToPLCexampleTemporary()
        {
            S7.SetIntAt(BufferWrite, 2, -10);
            int Result = m_s7Client.DBWrite(1, 0, 10, BufferWrite);

            S7MultiVar Reader = new S7MultiVar(m_s7Client);
            Reader.Add(S7Consts.S7AreaDB, S7Consts.S7WLByte, 1, 0, 10, ref Buffer);
            Result = Reader.Read();

            int a = S7.GetIntAt(Buffer, 2);

        }
It returns 65526 instead of -10

I propose this solution
        public static int GetIntAt(byte[] Buffer, int Pos)
        {
            return (int)(**(Int16)**((Buffer[Pos] << 8) | Buffer[Pos + 1]));
        }

**Comment by mesta1** [comment]
I verified the code and I had the same issue. I will contact the author to update the library,

**Comment by mesta1** [comment]
Fixed in Sharp7 1.0.3. 

Updated the example with the latest sources.

Thanks for the contribution.
